name: antiscam

on:
  issue_comment:
    types:
      - created
      - edited
  discussion_comment:
    types:
      - created
      - edited

permissions:
  pull-requests: write
  issues: write

jobs:
  build:
    if: ${{ !github.event.issue.pull_request }}
    name: Antiscam
    runs-on: ubuntu-latest

    steps:
      - uses: sl1depengwyn/antiscam-action@main
        with:
          token: ${{ github.token }}
      - name: Debug event
        run: |
          echo '${{ toJSON(github.event) }}'
